spring:
  application:
    name: thinking-in-statemachine
  datasource:
    url: jdbc:mysql://localhost:3307/lite-mall?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false # 不再控制台显示 SQL
        format_sql: true
        use_sql_comments: true
server:
  port: 8081
